version: '3.7'

services:
# Postgre
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "grupo3"
    ports:
      - "15432:5432"
    volumes:
      - ./db_helpdesk_postgres_init.sql:/docker-entrypoint-initdb.d/db_helpdesk_postgres_init.sql
      - ./db_orders_postgres_init.sql:/docker-entrypoint-initdb.d/db_orders_postgres_init.sql
      - ./db_products_postgres_init.sql:/docker-entrypoint-initdb.d/db_products_postgres_init.sql
      - ./db_profiles_postgres_init.sql:/docker-entrypoint-initdb.d/db_profiles_postgres_init.sql         
    networks:
      - network-docker

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "grupo3@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "grupo3"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - network-docker

networks:
  network-docker:
    driver: bridge
