version: '3.7'

services:
# Postgre
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "grupo3"
    ports:
      - "15432:5432"
    volumes:
      - ./resources/data:/var/lib/postgresql/data
    networks:
      - network-docker

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "grupo3@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "grupo3"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - network-docker

networks:
  network-docker:
    driver: bridge
