paths:
  /api/products/{id}:
    get:
      tags:
        - Produtos - Rotas principais
      security: []
      description: Detalhes do produto
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto a ser exibido.
          schema:
            type : number
            format: int64
            minimum: 1
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  created_at: 
                    type: string
                    example: "2021-05-17T20:59:13.842-03:00"
                  updated_at:
                    type: string
                    example: "2021-05-17T20:59:13.955-03:00"
                  name:
                    type: string
                    example: O melhor livro do ano
                  description: 
                    type: boolean
                    example: Esse é o melhor livro do ano
                  product_category_id:
                    type: number
                    example: 1
                  price: 
                    type: number
                    example: 10000
                  json_data:
                    type: string
                    example: {}
                  productCategory: 
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      reated_at: 
                        type: string
                        example: "2021-05-17T20:59:13.842-03:00"
                      updated_at:
                        type: string
                        example: "2021-05-17T20:59:13.955-03:00"
                      description:
                        type: string
                        example: Livros

  /api/products/search?search=café:
    get:
      tags:
        - Produtos - Rotas principais
      security: []
      description: Busca de produto por palavra chave.
      produces:
        - application/json
      parameters:
        - name: search
          in: query
          required: true
          description: Palavra chave para pesquisar produtos.
          example: café
          schema:
            type : string
            format: string
            minimum: 1
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 4
                    created_at: 
                      type: string
                      example: "2021-05-17T20:59:13.842-03:00"
                    updated_at:
                      type: string
                      example: "2021-05-17T20:59:13.955-03:00"
                    name:
                      type: string
                      example: O melhor livro do ano
                    description: 
                      type: boolean
                      example: Esse é o melhor livro do ano
                    product_category_id:
                      type: number
                      example: 1
                    price: 
                      type: number
                      example: 10000
                    json_data:
                      type: string
                      example: {}
                    productCategory: 
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        reated_at: 
                          type: string
                          example: "2021-05-17T20:59:13.842-03:00"
                        updated_at:
                          type: string
                          example: "2021-05-17T20:59:13.955-03:00"
                        description:
                          type: string
                          example: Livros
                    
  /api/products:
    get:
      tags:
        - Produtos - Rotas Auxiliares
      security: []
      description: Listagem de produtos
      produces:
        - application/json
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 4
                    created_at: 
                      type: string
                      example: "2021-05-17T20:59:13.842-03:00"
                    updated_at:
                      type: string
                      example: "2021-05-17T20:59:13.955-03:00"
                    name:
                      type: string
                      example: O melhor livro do ano
                    description: 
                      type: boolean
                      example: Esse é o melhor livro do ano
                    product_category_id:
                      type: number
                      example: 1
                    price: 
                      type: number
                      example: 10000
                    json_data:
                      type: string
                      example: {}
                    productCategory: 
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        reated_at: 
                          type: string
                          example: "2021-05-17T20:59:13.842-03:00"
                        updated_at:
                          type: string
                          example: "2021-05-17T20:59:13.955-03:00"
                        description:
                          type: string
                          example: Livros

    post:
      tags:
        - Produtos - Rotas Auxiliares
      security: []
      description: Criação de produtos
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Livro"
                description:
                  type: string
                  example: "livro de drama"
                product_category_id:
                  type: number
                  example: 1
                price:
                  type: number
                  example: "10000"
                json_data:
                  type: string
                  example: {}
      responses: 
        '201':
          description: Created