/api/products-categories:
  get:
    tags:
      - Produtos - Rotas principais
    security: []
    description: Listagem de produtos mais vistos por categoria.
    produces:
      - application/json
    responses:
      '200':
        description:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  created_at: 
                    type: string
                    example: "2021-05-17T20:59:13.842-03:00"
                  updated_at:
                    type: string
                    example: "2021-05-17T20:59:13.955-03:00"
                  description:
                    type: string
                    example: Jessica Smith
                  product: 
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1,
                        created_at:
                          type: string
                          example: "2021-06-02T17:11:23.021-03:00"
                        updated_at:
                          type: string
                          example: "2021-06-02T17:11:25.148-03:00"
                        name:
                          type: string
                          example: "Livro"
                        description:
                          type: string
                          example: "livro de drama"
                        product_category_id:
                          type: number
                          example: 1
                        price:
                          type: number
                          example: "10000"
                        json_data:
                          type: string
                          example: {}
